### ISSUE TITLE
Remove hardcoded MIT license

### ISSUE THREAD

**Issue by kylef** [neonichu/Chocolat#3]
```swift
spec["license"] = "MIT"
```

This can easily result in people creating and releasing pod specs with the wrong license and could cause legal trouble (i.e, when someone uses a pod thinking it's MIT but actually it's not).

**Comment by neonichu** [comment]
The generated podspec intentionally doesn't validate, so that people have to look at it, but maybe that's not enough.

**Comment by kylef** [comment]
I think even so, I would like to see the default license removed. A pod spec might not be generated by the  library author and the third party doing so might not care about figuring out the real license. Since this has legal implications we should remove it and force it to be set (CocoaPods already requires license).

**Comment by kylef** [comment]
Or a default of, if there is a `LICENSE` or `LICENSE.txt` file in the root directory, we infer it as:

```json
{
  "license": { "type": "Custom", "file": "LICENSE" }
}
```

While, at least it would automatically be valid but still allows setting a more concrete type.

**Comment by neonichu** [comment]
that sounds good :+1:
